### ISSUE TITLE
Color Palette does not appear on Piwigo 11.1.0

### ISSUE THREAD

**Issue by azharosman** [aNNiMON/Piwigo-Color-Palette#10]
Hello there. I noticed that Color Palette does not appear on photo details page on Piwigo version 11.1.0 as it should. On version 11,  it worked perfectly.

The extension is flagged as compatible in version 11 and now 11.1.0.

**Comment by aNNiMON** [comment]
@azharosman it's strange. I just updated my demo Piwigo instance and everything is fine there.
Did you update the themes? Are there any other plugins installed that might interfere with this plugin?

**Comment by azharosman** [comment]
Hi @aNNiMON, following your advice, I change the theme to the default and the problem persist. Then, I deactivate all other plugins except Color Palette. This worked!

To find out the cause of the problem, I reactivate the plugins one by one and check on the photo page to see if the color palette coming up or not. Finally, I found the conflicted plugin: 

Manage Properties Photos : https://piwigo.org/ext/extension_view.php?eid=783

It seems that this plugin/extension somewhat has overwritten the pallete's display. I checked and see that the plugin is compatible with piwigo version 11 just as the color palette.

Anyway, thanks for the lead.

**Comment by aNNiMON** [comment]
@azharosman thank you for information, it helped a lot! I've installed that plugin and now I can reproduce an issue. I see that he replaces an entire block of image information, which as a result prevents my plugin from displaying the palette. I'll contact the plugin developer to find a way to fix it.

**Comment by aNNiMON** [comment]
Just released a new version with the fix. Now it should work fine.
