### ISSUE TITLE
Ability to pick location of sample

### ISSUE THREAD

**Issue by fly-man-** [aNNiMON/Piwigo-Color-Palette#2]
If possible, I would like to be able to select the location inside the picture where it takes the sample.

Especially with large images, it takes a sample of the colors that are all the same

**Comment by aNNiMON** [comment]
Should this option be global for all images or just for single image?

**Comment by fly-man-** [comment]
I think for the usage that I have it needs to be one exact spot for each picture but I would think that other people might want to pick a certain spot like x,y coords

For me it would be good to have a pick that is the exact middle of the image.
