### ISSUE TITLE
Ability to select multiple colors

### ISSUE THREAD

**Issue by fly-man-** [aNNiMON/Piwigo-Color-Palette#3]
Would it be possible to have multiple selections, for example 3 colors, to match an image ?

One sample helps but with over 10.000 images I'd like to be able to distinct even more then with just 1 color.

**Comment by aNNiMON** [comment]
I'll think about this. The main problem is how to select 2+ colors in UI. <kbd>Shift+Click</kbd> on palette, checkboxes on hover or sequentially choosing colors?

**Comment by fly-man-** [comment]
Or perhaps select the colors and have a button there to combine the both in the request

Like 
[Red] [Green] Blue Yellow Orange  - [Search]

That way the Red and Green would be the 2 that you want to check on
