### ISSUE TITLE
Security bug?

### ISSUE THREAD

**Issue by tnovak007** [aNNiMON/Piwigo-Color-Palette#6]
Hi!
I encountered pretty serious bug with this plugin I think.
The palette search shows pictures from private albums, even for guests! When I click them, I got access denied, but the thumbs are visible!
I found it out by coincidence when I found images from private albums on Google image search - so it was evident they were exposed for guest access!
Please check the code, because without a fix it's impossible to use it for me.
Thanks.
Tom

**Comment by aNNiMON** [comment]
Thank you! I've already released a new version with fixes.

The problem was really on my side. I thought that Piwigo was doing further privacy checks when displaying a list of images, but this was not so.
Sorry for the inconvenience.

**Comment by tnovak007** [comment]
Thank you very much for the fast fix! It's working now correctly! Now I'm using it again.
(And don't worry, the exposed pictures were not so private, only not intended for all. But some other users could have bigger issues without this fix...)
So thank you again for your work.
Tom
