### ISSUE TITLE
authorize user Piwigo-TranslationTeam

### ISSUE THREAD

**Issue by ddtddt** [aNNiMON/Piwigo-Color-Palette#9]
Hi :-)

For add your project on https://piwigo.org/translate, can you give acces to user Piwigo-TranslationTeam and say me it's ok ;-)

**Comment by aNNiMON** [comment]
Hello. I sent invitation to specified user. Do I need to take any additional actions?

**Comment by Piwigo-TranslationTeam** [comment]
Invitation accepted :-)

@ddtddt now you can commit from Lexiglot
